package error;

public enum CompilationErrorType {

SYNTAX_ERROR, ILLEGAL_CHARACTER, INTERNAL_LEXER_ERROR, INTERNAL_ERROR, STRING_LITERAL_REQUIRED, FUNCTION_REDEFINITION, NUMBER_LITERAL_REQUIRED, EXPECTING_ARGUMENT, EXPECTING_INSTRUCTIONS

}
